---
driver:
  name: vagrant
  box: bento/centos-7.3

provisioner:
  name: chef_zero
  require_chef_omnibus: 12

platforms:
  - name: centos-7.3

suites:
  - name: default
    run_list:
      - recipe[template::default]
    attributes:
